name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build supervisor
        uses: home-assistant/builder@2024.01.0
        with:
          args: |
            $BUILD_ARGS \
            --amd64 \
            --target /data \
            --cosign \
            --docker-hub xiaoxuhong \
            --generic latest

